// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "app-swapi",
    "version": "1"
  },
  "paths": {
    "/planet/show-from-database/{id}": {
      "get": {
        "summary": "app-swapi",
        "description": "Show a planet from database",
        "operationId": "app-swapi.get./dev/planet/show-from-database/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planet/show-all-from-database": {
      "get": {
        "summary": "app-swapi",
        "description": "Show all planets from database",
        "operationId": "app-swapi.get./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planet/show-from-swapi/{id}": {
      "get": {
        "summary": "app-swapi",
        "description": "show a planet from swapi",
        "operationId": "app-swapi.get./planet/show-from-swapi/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planet/get-from-swapi-save-to-database/{id}": {
      "get": {
        "summary": "app-swapi",
        "description": "Get a planet from swapi and save it to database",
        "operationId": "app-swapi.get./planet/get-from-swapi-save-to-database/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planet/save-to-database": {
      "post": {
        "summary": "app-swapi",
        "description": "Save a planet to database",
        "operationId": "app-swapi.get./planet/save-to-database",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Planet"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
  },
  "definitions": {
    "Planet": {
      "properties": {
        "nombre": {
          "title": "Planet.nombre",
          "type": "string"
        },
        "diametro": {
          "title": "Planet.diametro",
          "type": "string"
        },
        "periodo_rotacion": {
          "title": "Planet.periodo_rotacion",
          "type": "string"
        },
        "periodo_orbita": {
          "title": "Planet.periodo_orbita",
          "type": "string"
        },
        "clima": {
          "title": "Planet.clima",
          "type": "string"
        },
        "gravedad": {
          "title": "Planet.gravedad",
          "type": "string"
        },
        "terreno": {
          "title": "Planet.terreno",
          "type": "string"
        },
        "superficie_agua": {
          "title": "Planet.superficie_agua",
          "type": "string"
        },
        "poblacion": {
          "title": "Planet.poblacion",
          "type": "string"
        },
        "url": {
          "title": "Planet.url",
          "type": "string"
        },
        "f_creacion": {
          "title": "Planet.f_creacion",
          "type": "string"
        },
        "f_edicion": {
          "title": "Planet.f_edicion",
          "type": "string"
        }
      },
      "required": [
        "nombre",
        "diametro",
        "periodo_rotacion",
        "periodo_orbita",
        "clima",
        "gravedad",
        "terreno",
        "superficie_agua",
        "poblacion",
        "url",
        "f_creacion",
        "f_edicion"
      ],
      "additionalProperties": false,
      "title": "Planet",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};